name: Website Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build
              run: |
                  npm run build

            - name: Clean up folder
              run: |
                  rm -rf node_modules
                  rm -rf .git
                  rm -rf .github
                  rm -rf .vscode
                  rm -rf public
                  rm -rf src
                  rm .gitignore
                  rm package-lock.json
                  rm package.json
                  rm README.md
                  rm jsconfig.json
                  rm yarn.lock
                  rm -rf tests

            - name: Deploy
              run: |
                  mv dist/* .
